version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - my-network

  bookmark_service:
    image: toanpham123/bookmark_service:dev
    container_name: bookmark_service
    ports:
      - "8080:8080"
    env_file:
      - ./bookmark_service/.env
    depends_on:
      - redis
    networks:
      - my-network

  portal:
    image: ebvn/bookmark-app-portal:dev
    container_name: portal
    networks:
      - my-network   
    # ports:
    #   - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bookmark_service
      - portal
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
    name: bookmark_service_network

volumes:
  redis_data:
